### ISSUE TITLE
Saving Rocket static and template files

### ISSUE THREAD

**Issue by hyousef-rusty** [pyros2097/rust-embed#111]
I'd a look at rocket [example](https://github.com/pyros2097/rust-embed/blob/master/examples/rocket.rs) but my issue is different, I've the below code:
```rust
#![feature(decl_macro, proc_macro_hygiene)]
use rocket_contrib::templates::Template;
use rocket_contrib::serve::StaticFiles;
mod routes;

use rust_embed::RustEmbed;

#[derive(RustEmbed)]
#[folder = "static"]
struct Static;

#[derive(RustEmbed)]
#[folder = "templates"]
struct Templates;

fn main() {
        rocket::ignite()
        .attach(Template::fairing())
        .mount("/static",
                StaticFiles::from("static"))
        .mount("/", rocket::routes![routes::root::root])
        .launch();
}
```
And the app structure is as shown:
![image](https://user-images.githubusercontent.com/60115476/82837598-33f16400-9ed2-11ea-8802-a9880238fea0.png)

And my `Cargo.toml` is:
```toml
[dependencies]
rust-embed = {version = "5.5.1", features = ["interpolate-folder-path"]}
rocket = "0.4.4"
[dependencies.rocket_contrib]
version = "0.4.4"
defaullt-features = "false"
features = ["tera_templates", "serve"]
```

Once I got the `.exe` file generated at `Win 10` it did not work without copying the `static` and `templates` folder in the same directory of the executable, am I missing something to get them embed in the binary itself?
