### ISSUE TITLE
actix example doesn't work (resolved)

### ISSUE THREAD

**Issue by ricjac** [pyros2097/rust-embed#64]
Hi,

I'm trying to get the actix example working in it's own new project.

But I get the following error:

**no method named `as_ref` found for type `mime_guess::Mime` in the current scope**
src/main.rs:22:61

```
$ cargo build 
Compiling embed_actix v0.1.0 (/home/rj/src/embed_actix)
error[E0599]: no method named `as_ref` found for type `mime_guess::Mime` in the current scope
--> src/main.rs:22:61
   |
22 |       HttpResponse::Ok().content_type(guess_mime_type(path).as_ref()).body(body)`
   |                                                             ^^^^^
```

cargo.toml:
```toml
[package]
name = "embed_actix"
version = "0.1.0"
authors = ["me <me@test.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
rust-embed = "4.4.0"
mime_guess = "1.8.7"
```

**src/main.rs** is copy of (with no changes):
[examples/actix.rs](https://github.com/pyros2097/rust-embed/blob/master/examples/actix.rs)

**Mime** is defined as
```rust
#[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd)]
pub struct Mime<T: AsRef<[Param]> = Vec<Param>>(pub TopLevel, pub SubLevel, pub T);
```
so should have the **as_ref** trait?

Any help to get this working would be great - thanks!

**Comment by ricjac** [comment]
I have tried updating my cargo.toml file to this, but still the same error:

```toml
[dependencies]
actix-web = "0.7"
futures = "0.1.27"
bytes = "0.4.12"
mime_guess = "1.8.7"
rust-embed-impl = "4.4.0"
rust-embed = { version = "4.4.0", features = ["actix", "debug-embed"] }
```
